name: CI 🧪

on:
  workflow_dispatch: {}
  pull_request: {}
  push: { branches: [main, develop] }

jobs:
  ###############################
  #             Test            #
  ###############################
  test:
    name: ${{ matrix.testMode }} ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
          - PlayMode
    steps:

      # This destroys 2GB free quota within a day
      #      - uses: actions/checkout@v2
      #        with:
      #          lfs: true

      # Workaround: https://github.com/actions/checkout/issues/165#issuecomment-657673315
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          rm .lfs-assets-id

      - name: Restore Library cache
        uses: actions/cache@v2
        id: lib-cache
        with:
          path: Library
          key: Library-Test
          restore-keys: |
            Library-

      - name: Test run
        uses: game-ci/unity-test-runner@v2.0-alpha-5
        id: testRunner
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.testMode }} test results
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Test results (${{ matrix.testMode }})
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  ###############################
  #            Build            #
  ###############################
  build:
    name: ${{ matrix.targetPlatform }} 🚀
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      # This destroys 2GB free quota within a day
      #      - uses: actions/checkout@v2
      #        with:
      #          lfs: true

      # Workaround: https://github.com/actions/checkout/issues/165#issuecomment-657673315
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          rm .lfs-assets-id

      - name: Restore Library cache
        uses: actions/cache@v2
        id: lib-cache
        with:
          path: Library
          key: Library-Build-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-Build-
            Library-

      - name: Build project
        uses: game-ci/unity-builder@38695bb26e1c15f43419ed9ab30c4bb7f92db311
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build (${{ matrix.targetPlatform }})
          path: build/${{ matrix.targetPlatform }}
